# Generated by Django 3.2.4 on 2021-06-11 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo', max_length=200, verbose_name='Nombre')),
                ('apellido', models.CharField(blank=True, help_text='Apellido del Empleado', max_length=200, verbose_name='Apellido')),
                ('codigoValidacion', models.BigIntegerField(blank=True, null=True, verbose_name='Codigo Validacion')),
                ('cuit', models.BigIntegerField(blank=True, help_text='Cuit del Empleado', null=True, verbose_name='Cuit')),
                ('dni', models.BigIntegerField(blank=True, help_text='Documento del Empleado', verbose_name='DNI')),
                ('domicilio', models.CharField(blank=True, help_text='Dirección del empleado', max_length=200, null=True, verbose_name='Dirección')),
                ('fecha_ingreso', models.DateField(blank=True, help_text='Fecha de ingreso del empleado', verbose_name='Fecha de Ingreso')),
                ('fecha_nacimiento', models.DateField(blank=True, help_text='Fecha de nacimiento del empleado', verbose_name='Fecha de Nacimiento')),
                ('email', models.EmailField(blank=True, help_text='Email del empleado', max_length=254, null=True, verbose_name='Email')),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('No Info', 'No Info')], default='No Info', max_length=10)),
                ('telefono', models.BigIntegerField(blank=True, help_text='teléfono del empleado', null=True, verbose_name='Teléfono')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo', max_length=200, verbose_name='Nombre')),
                ('numero', models.BigIntegerField(blank=True, default=0, help_text='Numero de planta', verbose_name='Numero de planta')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo', max_length=200, verbose_name='Nombre')),
                ('cantMaxVisitantes', models.BigIntegerField(blank=True, default=0, help_text='Cantidad maxima de visitantes', verbose_name='Cantidad maxima de visitantes')),
                ('cantMaxPorGuia', models.BigIntegerField(blank=True, default=0, help_text='Cantidad maxima de visitantes por guia', verbose_name='Cantidad maxima de visitantes por guia')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo', max_length=200, verbose_name='Nombre')),
                ('caducidad', models.DateField(blank=True, help_text='Fecha de caducidad del Usuario', verbose_name='Caducidad')),
                ('constraseña', models.CharField(blank=True, help_text='Contraseña del usuario', max_length=30, verbose_name='Contraseña')),
                ('empleado', models.ForeignKey(blank=True, help_text='Empleado', on_delete=django.db.models.deletion.CASCADE, related_name='museo_usuario', related_query_name='museo_usuario', to='museo.empleado', verbose_name='Empleado')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo', max_length=200, verbose_name='Nombre')),
                ('fecha_fin', models.DateField(blank=True, help_text='Fecha fin de la Sesión', verbose_name='Fecha fin')),
                ('fecha_inicio', models.DateField(blank=True, help_text='Fecha inicio de la Sesión', verbose_name='Fecha inicio')),
                ('hora_inicio', models.TimeField(blank=True, help_text='Hora de inicio de la Sesion', verbose_name='Hora de inicio')),
                ('hora_fin', models.TimeField(blank=True, help_text='Hora de fin de la Sesion', verbose_name='Hora de fin')),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuario', on_delete=django.db.models.deletion.CASCADE, related_name='museo_sesion', related_query_name='museo_sesion', to='museo.usuario', verbose_name='Usuario')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo', max_length=200, verbose_name='Nombre')),
                ('superficie', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Superficie en m2', max_digits=15, verbose_name='Superficie')),
                ('planta', models.ForeignKey(blank=True, help_text='Planta de la sede', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='museo_sala', related_query_name='museo_sala', to='museo.planta', verbose_name='PlantaSede')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='planta',
            name='sede',
            field=models.ForeignKey(blank=True, help_text='Sede', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='museo_planta', related_query_name='museo_planta', to='museo.sede', verbose_name='Sede'),
        ),
        migrations.CreateModel(
            name='Pared',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo', max_length=200, verbose_name='Nombre')),
                ('alto', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Alto de pared.', max_digits=15, verbose_name='Alto')),
                ('ancho', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Ancho de pared.', max_digits=15, verbose_name='Ancho')),
                ('sala', models.ForeignKey(blank=True, help_text='Sala de la planta', on_delete=django.db.models.deletion.CASCADE, related_name='museo_pared', related_query_name='museo_pared', to='museo.sala', verbose_name='SalaPlanta')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='empleado',
            name='sede',
            field=models.ForeignKey(blank=True, help_text='Sede', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='museo_empleado', related_query_name='museo_empleado', to='museo.sede', verbose_name='Sede'),
        ),
    ]
