# Generated by Django 3.2.4 on 2021-06-11 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sesion',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='constraseña',
        ),
    ]
