# Generated by Django 3.2.4 on 2021-06-11 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museo', '0002_auto_20210611_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='constraseña',
            field=models.CharField(blank=True, help_text='Contraseña del usuario', max_length=30, verbose_name='Contraseña'),
        ),
    ]
