# Generated by Django 3.2.4 on 2021-06-13 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('museo', '0003_usuario_constraseña'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pared',
            name='alto',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Alto de pared', max_digits=15, verbose_name='Alto'),
        ),
        migrations.AlterField(
            model_name='pared',
            name='ancho',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Ancho de pared', max_digits=15, verbose_name='Ancho'),
        ),
        migrations.AlterField(
            model_name='pared',
            name='sala',
            field=models.ForeignKey(blank=True, help_text='Sala de la planta', on_delete=django.db.models.deletion.CASCADE, related_name='museo_pared', related_query_name='museo_pared', to='museo.sala', verbose_name='Sala'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='planta',
            field=models.ForeignKey(blank=True, help_text='Planta de la sede', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='museo_sala', related_query_name='museo_sala', to='museo.planta', verbose_name='Planta'),
        ),
    ]
