# Generated by Django 3.2.4 on 2021-06-13 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museo', '0005_auto_20210613_2206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sesion',
            options={'ordering': ['usuario'], 'verbose_name': 'Sesion', 'verbose_name_plural': 'Sesiones'},
        ),
    ]
